POST https://672e4eeb229a881691efaeb3.mockapi.io/API/retaguardashop/Retaguardashop
Content-Type: application/json

{
  "nritem": "1",
  "descricao": "Otimização Postgre",
  "dtcriacao": "2024-11-19T23:18:04.720Z",
  "link": "https://docs.google.com/document/d/1_4VpAImmpUc5WhlzUl4XDCcz-JBAiJuIYfJIgPSVoCc/edit?usp=sharing",
  "tipo": "Comandos"
}


# ATALHO É "CTRL + ;"
# 
# 
# {
#   "nritem": "1",
#   "descricao": "Otimização Postgre",
#   "dtcriacao": "2024-11-19T23:18:04.720Z",
#   "link": "https://docs.google.com/document/d/1_4VpAImmpUc5WhlzUl4XDCcz-JBAiJuIYfJIgPSVoCc/edit?usp=sharing",
#   "tipo": "Comandos"
# }
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 
# 