put https://63069afec0d0f2b8011f9944.mockapi.io/produtos/50
Content-Type: application/json

{
"loja": "TechShop",
"descProd": "Cadeira Gamer Flexform Delta Black N Red",
"detalhes":"A cadeira DELTA atende todas as expectativa para os amantes da cadeira Gamer. Unificando conforto, design, tecnologia e alta performance, proporcionando a melhor experiência.",
"logoFab": "https://blog.flexform.com.br/wp-content/uploads/2019/12/flexform-white.png",
"fotoProd": "https://assets.betalabs.net/production/flexform/item-images/f0b4ad0e16e743828ed4250c18ba1c59.png",
"precoProd": "R$ 1.799,90",
"estoque": "4 un"
}



